# Render deployment configuration for ScreenSage Architect
services:
  # Backend API Service
  - type: web
    name: screensage-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: CORS_ORIGINS
        value: '["https://screensage-frontend.onrender.com"]'
      - key: DEBUG
        value: false
    healthCheckPath: /health
    
  # Frontend Service
  - type: web
    name: screensage-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://screensage-backend.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://screensage-backend.onrender.com/ws

  # Redis Service (using external provider)
  # Note: Use Redis Cloud free tier or similar
  
databases:
  # PostgreSQL database (optional)
  - name: screensage-db
    databaseName: screensage
    user: screensage